# Generated by Django 3.1.6 on 2021-04-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210405_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('in_progress', 'Заказ в обработке'), ('new', 'Новый заказ')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
