# Generated by Django 3.2 on 2021-04-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210427_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('in_progress', 'Заказ в обработке')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
